from __future__ import annotations

ColumnSpec = tuple[str, str, str]
TableSpec = tuple[str, str, tuple[ColumnSpec, ...]]


def col(name: str, sql_type: str = "TEXT") -> ColumnSpec:
    return ("col", name, sql_type)


def pk(name: str, sql_type: str = "TEXT") -> ColumnSpec:
    return ("pk", name, sql_type)


CORE_TABLE_SPECS = (
    ("plan_registry", "projection", (
        pk("plan_id"),
        col("kind"),
        col("layer"),
        col("sub_doc"),
        col("drive"),
        col("status"),
        col("parent"),
        col("updated_at"),
        col("decision_outcome"),
        col("source_hash"),
    )),
    ("artifact_registry", "projection", (
        pk("artifact_id"),
        col("artifact_type"),
        col("path"),
        col("pair_artifact"),
        col("status"),
        col("updated_at"),
    )),
    ("functional_registry", "projection", (
        pk("fn_id"),
        col("fr_id"),
        col("layer"),
        col("maps_to"),
        col("registry_hash"),
    )),
    ("trace_edges", "projection", (
        pk("edge_id"),
        col("from_artifact"),
        col("to_artifact"),
        col("edge_kind"),
        col("plan_id"),
        col("status"),
    )),
    ("coverage", "projection", (
        pk("coverage_id"),
        col("scope"),
        col("subject_id"),
        col("metric"),
        col("value", "REAL"),
        col("threshold", "REAL"),
        col("status"),
    )),
    ("findings", "projection", (
        pk("finding_id"),
        col("kind"),
        col("severity"),
        col("subject_id"),
        col("source"),
        col("status"),
        col("evidence_path"),
    )),
    ("gate_runs", "projection", (
        pk("gate_run_id"),
        col("gate_id"),
        col("plan_id"),
        col("status"),
        col("checked_at"),
        col("evidence_path"),
    )),
    ("drive_runs", "projection", (
        pk("drive_run_id"),
        col("plan_id"),
        col("session_id"),
        col("drive"),
        col("mode"),
        col("layer"),
        col("kind"),
        col("started_at"),
        col("completed_at"),
        col("status"),
    )),
    ("model_runs", "projection", (
        pk("run_id"),
        col("runtime"),
        col("model"),
        col("role"),
        col("drive"),
        col("plan_id"),
        col("started_at"),
        col("completed_at"),
        col("evidence_path"),
        col("input_tokens", "INTEGER"),
        col("output_tokens", "INTEGER"),
        col("cached_input_tokens", "INTEGER"),
        col("reasoning_tokens", "INTEGER"),
        col("cost_usd", "REAL"),
    )),
    ("skill_invocations", "projection", (
        pk("skill_invocation_id"),
        col("session_id"),
        col("plan_id"),
        col("skill_id"),
        col("layer"),
        col("drive"),
        col("fired_at"),
        col("source"),
        col("accepted", "INTEGER"),
    )),
    ("skill_recommendations", "projection", (
        pk("skill_recommendation_id"),
        col("session_id"),
        col("plan_id"),
        col("skill_id"),
        col("rank", "INTEGER"),
        col("score", "REAL"),
        col("reason"),
        col("recommended_at"),
    )),
    ("feedback_events", "projection", (
        pk("feedback_event_id"),
        col("finding_id"),
        col("plan_id"),
        col("source_table"),
        col("source_id"),
        col("source_color"),
        col("signal_type"),
        col("severity"),
        col("status"),
        col("next_action"),
        col("created_at"),
    )),
    ("quality_signals", "projection", (
        pk("signal_id"),
        col("source"),
        col("subject_id"),
        col("metric"),
        col("value", "REAL"),
        col("threshold", "REAL"),
        col("status"),
        col("computed_at"),
    )),
    ("test_runs", "projection", (
        pk("test_run_id"),
        col("session_id"),
        col("plan_id"),
        col("command"),
        col("runner"),
        col("runtime"),
        col("os"),
        col("shell"),
        col("scope"),
        col("started_at"),
        col("completed_at"),
        col("exit_code", "INTEGER"),
        col("evidence_path"),
        col("output_digest"),
        col("green_definition_id"),
        col("status"),
    )),
    ("test_cases", "projection", (
        pk("test_case_id"),
        col("test_run_id"),
        col("test_file"),
        col("test_name"),
        col("plan_id"),
        col("fr_id"),
        col("artifact_id"),
        col("kind"),
        col("oracle_id"),
        col("name"),
        col("first_seen_at"),
        col("last_seen_at"),
        col("status"),
        col("duration_ms", "REAL"),
        col("evidence_path"),
    )),
    ("test_results", "projection", (
        pk("test_result_id"),
        col("test_case_id"),
        col("test_run_id"),
        col("oracle_id"),
        col("status"),
        col("duration_ms", "REAL"),
        col("failure_digest"),
        col("started_at"),
        col("completed_at"),
        col("message"),
        col("evidence_path"),
    )),
    ("test_result_events", "append_event", (
        pk("event_id"),
        col("ut_id"),
        col("run_id"),
        col("seq"),
        col("status"),
        col("run_at"),
        col("command"),
        col("digest"),
    )),
    ("test_artifact_edges", "projection", (
        pk("edge_id"),
        col("test_artifact_edge_id"),
        col("test_case_id"),
        col("test_run_id"),
        col("artifact_id"),
        col("plan_id"),
        col("source_path"),
        col("artifact_path"),
        col("edge_kind"),
        col("oracle_id"),
        col("evidence_path"),
    )),
    ("test_flake_events", "projection", (
        pk("flake_event_id"),
        col("test_case_id"),
        col("window"),
        col("pass_count", "INTEGER"),
        col("fail_count", "INTEGER"),
        col("flake_score", "REAL"),
        col("computed_at"),
        col("evidence_path"),
    )),
    ("search_index", "projection", (
        pk("search_id"),
        col("subject_type"),
        col("subject_id"),
        col("path"),
        col("title"),
        col("tokens"),
        col("summary"),
        col("updated_at"),
    )),
    ("workflow_runs", "projection", (
        pk("workflow_run_id"),
        col("plan_id"),
        col("drive_run_id"),
        col("workflow"),
        col("phase"),
        col("ready_status"),
        col("blocked_reason"),
        col("human_required", "INTEGER"),
        col("checked_at"),
    )),
    ("guardrail_decisions", "append_event", (
        pk("guardrail_decision_id"),
        col("plan_id"),
        col("session_id"),
        col("guardrail"),
        col("decision"),
        col("mode"),
        col("human_signoff_required", "INTEGER"),
        col("evidence_path"),
        col("decided_at"),
    )),
    ("hook_events", "append_event", (
        pk("event_id"),
        col("session_id"),
        col("plan_id"),
        col("hook_name"),
        col("event_type"),
        col("occurred_at"),
        col("digest"),
        col("evidence_path"),
    )),
    ("issue_queue", "projection", (
        pk("issue_queue_id"),
        col("source_event_id"),
        col("plan_id"),
        col("target"),
        col("title"),
        col("body"),
        col("status"),
        col("human_approval_required", "INTEGER"),
        col("approved_by"),
        col("approved_at"),
        col("external_issue_id"),
        col("external_issue_url"),
        col("created_at"),
    )),
    ("trouble_events", "projection", (
        pk("trouble_event_id"),
        col("source_event_id"),
        col("plan_id"),
        col("category"),
        col("severity"),
        col("summary"),
        col("status"),
        col("created_at"),
    )),
    ("retry_events", "projection", (
        pk("retry_event_id"),
        col("plan_id"),
        col("workflow"),
        col("phase"),
        col("attempt_count", "INTEGER"),
        col("status"),
        col("created_at"),
    )),
    ("improvement_log", "projection", (
        pk("improvement_log_id"),
        col("source_event_id"),
        col("plan_id"),
        col("category"),
        col("summary"),
        col("next_action"),
        col("status"),
        col("created_at"),
    )),
    ("automation_assets", "projection", (
        pk("asset_id"),
        col("asset_type"),
        col("path"),
        col("trigger"),
        col("role"),
        col("capability"),
        col("skill_type"),
        col("applies_layers"),
        col("applies_drive_models"),
        col("drift_status"),
        col("indexed_at"),
    )),
)
