from __future__ import annotations

ColumnSpec = tuple[str, str, str]
TableSpec = tuple[str, str, tuple[ColumnSpec, ...]]


def col(name: str, sql_type: str = "TEXT") -> ColumnSpec:
    return ("col", name, sql_type)


def pk(name: str, sql_type: str = "TEXT") -> ColumnSpec:
    return ("pk", name, sql_type)


GRAPH_TABLE_SPECS = (
    ("graph_nodes", "projection", (
        pk("node_id"),
        col("node_type"),
        col("subject_id"),
        col("section_id"),
        col("path"),
        col("name"),
        col("layer"),
        col("kind"),
        col("status"),
        col("source"),
        col("indexed_at"),
    )),
    ("dependency_edges", "projection", (
        pk("edge_id"),
        col("from_node_id"),
        col("to_node_id"),
        col("edge_kind"),
        col("strength", "REAL"),
        col("source"),
        col("evidence_path"),
        col("is_expected", "INTEGER"),
        col("is_actual", "INTEGER"),
        col("indexed_at"),
    )),
    ("impact_rules", "config", (
        pk("impact_rule_id"),
        col("trigger_edge_kind"),
        col("trigger_node_type"),
        col("required_node_type"),
        col("required_action"),
        col("severity"),
        col("gate"),
        col("enabled", "INTEGER"),
    )),
    ("impact_results", "projection", (
        pk("impact_result_id"),
        col("change_set_id"),
        col("root_node_id"),
        col("impacted_node_id"),
        col("required_action"),
        col("status"),
        col("reason"),
        col("evidence_path"),
        col("computed_at"),
    )),
    ("artifact_progress", "projection", (
        pk("artifact_path"),
        col("artifact_type"),
        col("artifact_hash"),
        col("state"),
        col("color"),
        col("linked_test_ids"),
        col("linked_test_paths"),
        col("linked_test_count", "INTEGER"),
        col("passed_test_run_ids"),
        col("passed_test_run_count", "INTEGER"),
        col("dependency_checked", "INTEGER"),
        col("dependency_check_run_id"),
        col("dependency_checked_at"),
        col("dependency_check_source"),
        col("open_dependency_impacts", "INTEGER"),
        col("recovery_plan_ids"),
        col("reason"),
        col("indexed_at"),
    )),
    ("artifact_progress_events", "projection", (
        pk("artifact_progress_event_id"),
        col("artifact_path"),
        col("artifact_type"),
        col("previous_color"),
        col("color"),
        col("state"),
        col("trigger"),
        col("test_run_ids"),
        col("dependency_check_run_id"),
        col("recovery_plan_ids"),
        col("reason"),
        col("occurred_at"),
    )),
    ("tool_runs", "projection", (
        pk("tool_run_id"),
        col("tool_name"),
        col("tool_version"),
        col("command"),
        col("input_scope"),
        col("exit_code", "INTEGER"),
        col("started_at"),
        col("completed_at"),
        col("evidence_path"),
    )),
    ("diagram_artifacts", "projection", (
        pk("diagram_id"),
        col("graph_snapshot_id"),
        col("format"),
        col("path"),
        col("renderer"),
        col("scope"),
        col("created_at"),
        col("evidence_path"),
    )),
    ("graph_snapshots", "projection", (
        pk("graph_snapshot_id"),
        col("scope"),
        col("node_count", "INTEGER"),
        col("edge_count", "INTEGER"),
        col("hash"),
        col("created_at"),
        col("source_digest"),
    )),
    ("mcp_server_profiles", "config", (
        pk("mcp_profile_id"),
        col("name"),
        col("package_ref"),
        col("source_url"),
        col("transport"),
        col("command"),
        col("args_digest"),
        col("allowed_tools"),
        col("read_only", "INTEGER"),
        col("requires_network", "INTEGER"),
        col("requires_docker", "INTEGER"),
        col("requires_auth", "INTEGER"),
        col("risk_tier"),
        col("enabled", "INTEGER"),
        col("source"),
        col("indexed_at"),
    )),
    ("mcp_profile_triggers", "config", (
        pk("trigger_id"),
        col("mcp_profile_id"),
        col("signal"),
        col("workflow"),
        col("layer"),
        col("gate"),
        col("reason"),
        col("enabled", "INTEGER"),
    )),
    ("verification_profiles", "config", (
        pk("verification_profile_id"),
        col("name"),
        col("profile_type"),
        col("package_refs"),
        col("requires_docker", "INTEGER"),
        col("requires_browser", "INTEGER"),
        col("requires_network", "INTEGER"),
        col("green_definition_id"),
        col("trigger_signals"),
        col("enabled", "INTEGER"),
    )),
    ("verification_recommendations", "projection", (
        pk("verification_recommendation_id"),
        col("change_set_id"),
        col("plan_id"),
        col("profile_id"),
        col("profile_kind"),
        col("reason"),
        col("source_rule"),
        col("accepted", "INTEGER"),
        col("created_at"),
    )),
    ("mcp_server_runs", "projection", (
        pk("mcp_run_id"),
        col("mcp_profile_id"),
        col("session_id"),
        col("plan_id"),
        col("command"),
        col("method"),
        col("tool_name"),
        col("started_at"),
        col("completed_at"),
        col("exit_code", "INTEGER"),
        col("evidence_path"),
        col("normalized_status"),
    )),
    ("external_tool_findings", "projection", (
        pk("external_finding_id"),
        col("source_run_id"),
        col("source_kind"),
        col("finding_type"),
        col("severity"),
        col("subject_id"),
        col("path"),
        col("status"),
        col("digest"),
        col("created_at"),
    )),
    ("document_export_profiles", "config", (
        pk("document_export_profile_id"),
        col("name"),
        col("source_doc_family"),
        col("format"),
        col("renderer"),
        col("package_ref"),
        col("source_url"),
        col("built_in", "INTEGER"),
        col("requires_package", "INTEGER"),
        col("requires_d2", "INTEGER"),
        col("enabled", "INTEGER"),
        col("risk_tier"),
        col("trigger_signals"),
    )),
    ("document_export_runs", "projection", (
        pk("document_export_run_id"),
        col("profile_id"),
        col("session_id"),
        col("plan_id"),
        col("source_doc_family"),
        col("source_paths_digest"),
        col("source_snapshot_hash"),
        col("redaction_profile"),
        col("started_at"),
        col("completed_at"),
        col("exit_code", "INTEGER"),
        col("evidence_path"),
        col("normalized_status"),
    )),
    ("document_export_datasets", "projection", (
        pk("document_export_dataset_id"),
        col("export_run_id"),
        col("dataset_kind"),
        col("row_count", "INTEGER"),
        col("column_digest"),
        col("source_paths"),
        col("source_section_digest"),
        col("created_at"),
        col("hash"),
        col("format"),
    )),
    ("document_export_artifacts", "projection", (
        pk("document_export_artifact_id"),
        col("export_run_id"),
        col("format"),
        col("path"),
        col("renderer"),
        col("byte_size", "INTEGER"),
        col("hash"),
        col("created_at"),
        col("evidence_path"),
        col("stale_status"),
    )),
    ("document_export_triggers", "config", (
        pk("trigger_id"),
        col("document_export_profile_id"),
        col("signal"),
        col("workflow"),
        col("layer"),
        col("gate"),
        col("reason"),
        col("enabled", "INTEGER"),
    )),
)
